import { AddLeadPayload } from '../components/AddLeadConfirmModal';
export interface NewLeadRecord { id:string; createdAt:string; clientName:string; clientPhone:string; clientEmail:string; address:string; leadSource:string; angiAccount?: 'not_identified'|'dxg'|'mr_contract'; serviceNeeded:string; status:string; notes:string; leadFee?:string; rowIndex?:number; statusColIndex?:number; isWebhookLead?:boolean; webhookSource?:string; sheetSynced?:boolean; houzzResult?:string; houzzStatus?:string; houzzError?:string|null; houzzStatusCode?:number|null; houzzAttemptAt?:string; rawPayload?:any; }
const EVENT_KEY='new_leads_updated'; let canonicalLeads:NewLeadRecord[]=[]; let requestInFlight:Promise<NewLeadRecord[]>|null=null;
function publish(list:NewLeadRecord[]){ canonicalLeads=[...list].sort((a,b)=>new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()); window.dispatchEvent(new CustomEvent(EVENT_KEY,{detail:canonicalLeads})); return canonicalLeads; }
export function getNewLeads(){ return canonicalLeads; }
export async function fetchNewLeads(forceFresh=false){ if(requestInFlight)return requestInFlight; requestInFlight=(async()=>{const res=await fetch(`/api/leads?status=New${forceFresh?'&force=1':''}`); const data=await res.json().catch(()=>({})); if(!res.ok||!data.success||!Array.isArray(data.leads))throw new Error(data.error||'Unable to load leads.'); return publish(data.leads);})(); try{return await requestInFlight;}finally{requestInFlight=null;} }
export async function migrateLegacyNewLeads(){ return {migrated:0,skipped:0}; }
export async function addNewLead(payload:AddLeadPayload){const res=await fetch('/api/leads/manual',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json().catch(()=>({}));if(!res.ok||!data.success)throw new Error(data.error||'Failed to save lead.');const lead=data.lead as NewLeadRecord;publish([lead,...canonicalLeads.filter(x=>x.id!==lead.id)]);void fetchNewLeads(false).catch(()=>{});return lead;}
export async function deleteNewLead(id:string){const res=await fetch(`/api/leads/${encodeURIComponent(id)}`,{method:'DELETE'});const data=await res.json().catch(()=>({}));if(!res.ok||!data.success)throw new Error(data.error||'Failed to delete lead from Firestore.');publish(canonicalLeads.filter(x=>x.id!==id));}
export function updateNewLeadStatus(id:string,status:string){publish(canonicalLeads.map(x=>x.id===id?{...x,status}:x).filter(x=>x.status.toLowerCase()==='new'));}
export function updateNewLeadInfo(id:string,updates:Partial<NewLeadRecord>){publish(canonicalLeads.map(x=>x.id===id?{...x,...updates}:x));}
